${GRIPPER_SUFFIX}_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - ${GRIPPER_SUFFIX}_thumb_joint
      - ${GRIPPER_SUFFIX}_index_joint
      - ${GRIPPER_SUFFIX}_mrl_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.75
      ${GRIPPER_SUFFIX}_thumb_joint:
        goal: &hand_goal_pos_constraint 0.3
      ${GRIPPER_SUFFIX}_index_joint:
        goal: 0.6
      ${GRIPPER_SUFFIX}_mrl_joint:
        goal: *hand_goal_pos_constraint
      stop_trajectory_duration: 0.0
